### PR TITLE
Recursive macros

### PR DESCRIPTION
**Pull request by piernov**
Forgot to PR that earlier…

### CODE REVIEW

**Review by sticmac — APPROVED** [review]
So is there anything more wanted to merge this pull request?

**Comment by piernov** [comment]
Other members comments and eventually approval.

**Comment by sticmac** [comment]
@piernov Yeah would be great. @Tordesillas @NassimBounouas

**Review by Tordesillas — APPROVED** [review]

**Comment by piernov** [comment]
If #60 is merged, this PR can be closed.

**Pull request closed without merging**
